#!/bin/bash
/Applications/ffmpeg -f avfoundation -r 30 -i "0"  -frames:v 1 ~/Library/Mobile\ Documents/com~apple~CloudDocs/PasswordWrong/vid-$ts.%01d.png
exit 0  #important - has to exit with status 0
